version : '3.5'

services: 

   postgres:
      build:
         context: .
         dockerfile: "postgres.Dockerfile"
      ports:
         - '5433:5432'
      container_name: 'db'
    
   api:
      build :
            context: .
            dockerfile: 'api.Dockerfile' 
      links:
         - 'postgres'     
      extra_hosts:
         - "inDockerHost:172.17.0.1"   
      ports:
         - '5000:80'
      depends_on:
         - 'postgres'

        